### ISSUE TITLE
Question about plans for package maintenance

### ISSUE THREAD

**Issue by kristof-siket** [lagunovsky/redux-react-router#11]
Hello,

I'm creating this issue because the package seems to be very promising to me and I have not found any alternative for the connected-react-router that is compatible with the newest versions of react router.

I'm wondering whether the current 2 contributors plan to continue the maintenance of the package in long term? 🤔 Or, are you guys looking for contributors too? I saw on NPM that the weekly download is increasing and I guess if there is no bigger concurrency, this package could be the one that people use for this purpose 💪 

Thanks a lot so far and in advance.

**Comment by lagunovsky** [comment]
I will maintain this package as long as I have access to github 😉
