### ISSUE TITLE
Have an issue The prop `history` is marked as required in `Router`, but its value is `undefined`.

### ISSUE THREAD

**Issue by Kost927** [lagunovsky/redux-react-router#12]
But it is there. As you can see in the first screenshot history obj comes not undefined.
<img width="433" alt="Screenshot 2022-09-12 at 11 48 12" src="https://user-images.githubusercontent.com/64188262/189612194-d3812b6c-bc97-4ffa-ac0c-81576eaf998f.png">
<img width="801" alt="Screenshot 2022-09-12 at 11 51 07" src="https://user-images.githubusercontent.com/64188262/189612342-ff20f263-6196-41db-bf2d-70bdeaf2177a.png">
<img width="779" alt="Screenshot 2022-09-12 at 11 51 49" src="https://user-images.githubusercontent.com/64188262/189612498-b91d1aa6-9d63-4dff-afa9-06a74ab80fcd.png">
package.json:
"history": "^5.3.0",
"react-router-dom": "^6.3.0",
"@lagunovsky/redux-react-router": "^4.0.0"

**Comment by Kost927** [comment]
using debugger can see that the history obj comes not complete. Any suggestions on how to fix it?
<img width="483" alt="Screenshot 2022-09-12 at 12 11 32" src="https://user-images.githubusercontent.com/64188262/189616590-9135a206-c05d-4d6b-94a4-bc5f0f2f2b13.png">

**Comment by Kost927** [comment]
Sorry, react-router was not updated to 6th version, only react router dom.

**Comment by Kost927** [comment]
Also had a problem with history dep. Tried 4.10.* and 5.3.0 (latest), and tried to remove history dep at all, as it is present in react-router-dom. Always had errors. The solution is to use history 5.0.0.

**Comment by lagunovsky** [comment]
Doesn't work with 5.3 and works with 5.0, am I right?

**Comment by Kost927** [comment]
Yes, you are right
