### ISSUE TITLE
Cannot read properties of undefined (reading 'action')

### ISSUE THREAD

**Issue by itschip** [lagunovsky/redux-react-router#13]
![image](https://user-images.githubusercontent.com/59088889/189869645-9594f943-9b1d-4ce7-ae01-fd35b1ae1148.png)
I seem to be having an issue with this. The error seems to occurr from the ReduxRouter provider, or atleast where it is called.

I am using
```json
    "react-dom": "^18.2.0",
    "react-router": "^6.3.0",
    "react-redux": "^8.0.2",
    "react-router-dom": "^6.3.0",
    "react-scripts-ts": "2.17.0",
    "redux": "^4.2.0",
    "redux-saga": "^0.16.0",
    "redux-thunk": "^2.2.0",
```
```js
import {createBrowserHistory} from "history";


const history = createBrowserHistory()
const store = configureStore(history, {}, rootSaga);

const render = () => {
	createRoot(document.getElementById("root") as HTMLElement).render(
		<Provider store={store}>
			<ReduxRouter history={history}>
				<App/>
			</ReduxRouter>
		</Provider>,
	);
}

render();
```
Any suggestions?

**Comment by lagunovsky** [comment]
What version of the `history` package are you using?
Where and how do you use `createRouterReducer`?
What does `reduxRouterSelector` return when it is called in the `render()`?

Could you create a repository with your build environment?

**Comment by itschip** [comment]
I figured it out....called my router reducer `routing` instead `router`. I could've used a custom selector but eh.
