### ISSUE TITLE
Storing reducer with custom key

### ISSUE THREAD

**Issue by mpopov** [lagunovsky/redux-react-router#18]
Since we have a constant `const ROUTER_REDUCER_MAP_KEY = 'router'` storing reducer with key `'navigator'` like in example doesn't work:
`const rootReducer = combineReducers({ navigator: createRouterReducer(history) })`

**Comment by lagunovsky** [comment]
This constant is only used in the built-in selector.

You need to use the `routerSelector`: `<ReduxRouter history={history} routerSelector={state => state.navigator}/>`

**Comment by mpopov** [comment]
I've tried to use action creators, didn't even use selector, copied that `combineReducers` line with `'navigator'` and have a bunch of errors _'TypeError: state is undefined'_ from inside a bundle, not my code. Than renamed key to `'router'` and everything works like a charm. Let me double check in more simple example a bit later :)
