### ISSUE TITLE
Using createBrowserRouter and other same functions

### ISSUE THREAD

**Issue by Tsyklop** [lagunovsky/redux-react-router#19]
I need use [createHashRouter](https://reactrouter.com/en/main/routers/create-hash-router) function. How i can use it with your library?

**Comment by lagunovsky** [comment]
This api is not yet supported.


Alternatively:
```ts
import { createMemoryHistory } from 'history'
const history = createMemoryHistory()
```

**Comment by Tsyklop** [comment]
@lagunovsky is there any future support planned?

**Comment by lagunovsky** [comment]
Duplicate #15
