### ISSUE TITLE
React-redux v8 not supported

### ISSUE THREAD

**Issue by ayxos** [lagunovsky/redux-react-router#6]
The new React-redux version (v8) is , in theory, fully backward compatible. (https://github.com/reduxjs/react-redux/releases)
Is there any way to support also this version?

**Comment by faminchik** [comment]
@ayxos, agree, works completely fine with the `react-redux` **v8**

**Comment by lagunovsky** [comment]
I'll take a look at it soon.

**Comment by lagunovsky** [comment]
Works correctly with the react-redux v8
